endlessm/azafea

azafea/event_processors/ping/v1.py
setup.cfg
setup.py

This removes some unnecessary debug output, removes an unused pytest marker, adds a py.typed file for mypy, and moves to a declarative build system.

A few changes

---

.travis.yml

ci: Set up Travis

---

Pipfile
Pipfile.lock

The actual thing in this merge request that I'm happy about is we can finally stop using my fork of mypy and move to an upstream release.
The rest is just minor updates of some dependencies which happened to have a new release when I checked.

Update some deps

---

.travis.yml
CONTRIBUTING.md
Pipfile
azafea/tests/integration/__init__.py
azafea/tests/integration/managedb/handler_module.py
setup.cfg

Mostly trivial stuff, see the individual commit messages for details…

Some test/ci changes

---

Pipfile.lock
azafea/config/__init__.py
docs/source/event-handlers.rst

This fixes a copy-paste in the docs, upgrade some deps, and improves some internal API.

Misc changes

---

.gitignore
azafea/config/__init__.py

This was introduced without the validator to ensure this really is a
boolean.

config: Validate exit_on_empty_queues

---

Dockerfile
azafea/tests/test_cli.py

This removes unnecessary work from the Dockerfile and fixes a test when ran under Docker.

Docker and tests

---

azafea/__main__.py
azafea/cli.py
azafea/cli/__init__.py
azafea/cli/commands.py
azafea/cli/errors.py
azafea/config/__init__.py
azafea/event_processors/activation/tests/integration/test_activation_v1.py
azafea/event_processors/metrics/tests/integration/test_metrics_v2.py
azafea/event_processors/ping/tests/integration/test_ping_v1.py
azafea/tests/integration/__init__.py
azafea/tests/integration/managedb/test_managedb.py
azafea/tests/integration/nullableboolean/test_nullableboolean.py
azafea/tests/test_cli.py
azafea/tests/test_config.py

This paves the way for per-queue commands.

Refactor the CLI handling

---

azafea/event_processors/metrics/events/__init__.py

This patch implements the following metrics produced by the
com.hack_computer.Clubhouse app:
* HackClubhouseChangePage
* HackClubhouseEnterPathway
* HackClubhouseAchievementPoints
* HackClubhouseAchievement
* HackClubhouseProgress

metrics: Implement hack clubhouse metrics

---

Pipfile.lock
azafea/event_processors/metrics/events/_base.py
azafea/model.py

The new Mypy imposes a couple of changes to the type annotations, in
fact making them more correct.

Upgrade the dependencies

---

azafea/event_processors/activation/tests/integration/test_activation_v1.py
azafea/event_processors/activation/tests/test_activation_parsing.py
azafea/event_processors/ping/tests/integration/test_ping_v1.py
azafea/vendors.py

Looking at the existing data, we can find more things to deduplicate.

vendors: Add some more mapping

---

CONTRIBUTING.md
Dockerfile

This moves us to the container-based development workflow I've been using for a few months now.
It's especially interesting on immutable operating systems like Endless or Fedora Silverblue.

Embrace containers

---

azafea/event_processors/metrics/tests/integration/test_metrics_cli.py
azafea/model.py

Just a couple of trivial things I stumbled upon, see individual commits.

Misc trivial changes

---

azafea/cli/commands.py

cli: Print something when the migratedb command ends

---

azafea/event_processors/metrics/events/__init__.py
azafea/event_processors/metrics/tests/integration/test_metrics_cli.py
azafea/event_processors/metrics/tests/integration/test_metrics_v2.py
azafea/event_processors/metrics/v2/cli.py

Looking at the database, we have *many* requests which contain *lots* of image version events.
The most I found in production is a request with 139 identical image version events.
This does two things:
1. it filters incoming requests so that only a single image version event (at most) is added per request;
2. it brings in a new CLI tool to deduplicate the existing image version records so that the DB only contains one per request;

metrics: Deduplicate image version events

---

azafea/event_processors/metrics/v2/handler.py

The code was committing the request because if that failed (mostly
because the request was already known in the database) then we could
skip parsing all the events, which freed the worker earlier to process
another request.
However, it also meant that a request could be inserted, but an
unhandled exception later on would cause the rest of the transaction to
be aborted and the request to be pushed back into Redis.
At that point, trying to replay the request wouldn't help because the
request would already have been stored, and so it would just get
skipped, losing its associated events.
Clearly this is unacceptable, and that was a bad choice of optimization.
Fortunately, this never actually happened in production.
This commit fixes that, so the events are always parsed and the request
is …

metrics: Commit the request with its events

---

azafea/event_processors/endless/metrics/events/__init__.py
azafea/event_processors/endless/metrics/tests/test_events.py

Add several new metrics emitted from across the desktop to track how
widely parental controls are used and which parental controls settings
are used.
Signed-off-by: Philip Withnall <withnall@endlessm.com>
https://phabricator.endlessm.com/T28742

metrics: Add parental controls events

---

azafea/event_processors/endless/metrics/events/__init__.py
azafea/event_processors/endless/metrics/tests/test_events.py

Fix some incorrect parsing code from my last attempt, and add more tests.
https://phabricator.endlessm.com/T28742

T28742 Further parental controls fixes

---

azafea/event_processors/endless/metrics/v2/cli.py

These commands were retrieving the whole ShellAppIsOpen and OSVersion tables on
the Python backend server, chunk by chunk. This was too slow for the production
server data.
The new version proposed here still uses the ORM, but creates SQL-only requests
that can be launched on the PostgreSQL server. Chunked queries, used to avoid
the load of the whole tables in memory, are:
- useless because the data are not handled by Python, and
- impossible because SQLAlchemy (and I suppose PostgreSQL) cannot edit lines
using the LIMIT keyword.
remove-os-info-quotes is now applied even on rows where quotes have already
been removed. This no-op operation is probably as fast as filtering the lines
before trimming the string. That is why the command no longer tells when no row
has to be modified, and the …

Improve speed for set-open-durations and remove-os-info-quotes

---

azafea/cli/commands.py
azafea/event_processors/endless/metrics/request.py
azafea/event_processors/endless/metrics/tests/integration/test_metrics_cli.py
azafea/event_processors/endless/metrics/v2/migrations/e7c7d5f2e4df_materialized_view_for_metrics.py
azafea/model.py
azafea/tests/integration/__init__.py
azafea/tests/test_cli.py
azafea/tests/test_model.py

This view is useful to get active user reports.
We have to take a decision about the way the view is refreshed: an SQL command has to be sent regularly, probably once a day. @adarnimrod Do you have an idea?
https://phabricator.endlessm.com/T29216

Create materialized view listing machine ids grouped by day

---

azafea/event_processors/endless/metrics/events/__init__.py
azafea/event_processors/endless/metrics/tests/test_events.py
azafea/event_processors/endless/metrics/v2/migrations/5393df905032_add_eos_updater_failure_event.py

Signed-off-by: Philip Withnall <withnall@endlessm.com>
https://phabricator.endlessm.com/T29247

Add an event for eos-updater failures

---

azafea/event_processors/endless/metrics/events/__init__.py
azafea/event_processors/endless/metrics/events/_base.py

Store the "allowed empty payload" information in the table class

---

azafea/event_processors/endless/metrics/tests/integration/test_metrics_cli.py
azafea/event_processors/endless/metrics/v2/cli.py

Events with empty location info are now ignored, but they used to be accepted and put in the database. This command removes these useless empty locations from the database.
Fix https://phabricator.endlessm.com/T29561. Related to #115.

Add command removing events with empty location info

---

azafea/event_processors/endless/metrics/request.py
azafea/event_processors/endless/metrics/v2/migrations/29c26262aa70_add_day_index_on_machine_by_day_table.py

See https://phabricator.endlessm.com/T29216

Add day index on machine by day table

---

azafea/event_processors/endless/metrics/events/_base.py
azafea/event_processors/endless/metrics/v2/migrations/98078d059259_add_index_on_started_at_and_occured_at.py

**To be merged after #130.**
See https://phabricator.endlessm.com/T29220.

Add index on started_at and occured_at columns

---

azafea/event_processors/endless/metrics/utils.py

Remove variant getters

---

azafea/event_processors/endless/activation/tests/integration/test_activation_v1.py
azafea/event_processors/endless/ping/tests/integration/test_ping_v1.py

Fix also one of these tests.
(Probably conflicts with #135 with trivial merging solution.)

Add missing asserts in tests

---

.github/workflows/metabase.yml
.github/workflows/tests.yml
azafea/tests/test_processor.py

https://phabricator.endlessm.com/T31180
Secrets have to be added to this repository to allow deployments on Metabase (see #129).
Deployments on ReadTheDocs are possible using a simple webhook, no CI required.

Use GitHub instead of Travis

---

azafea/processor.py
azafea/tests/integration/__init__.py
azafea/tests/test_processor.py

This pull request includes two commits.
1. Use a very short timeout if we want to exit when the Redis queue is empty.
2. Use simple code to check that no table is in database (only used for tests).

Improve tests speed

---

azafea/event_processors/endless/metrics/request.py
azafea/event_processors/endless/metrics/v2/migrations/63365dc8695a_add_machine_id_index.py

Useful for T29216.
https://phabricator.endlessm.com/T29216

Add machine_id index on machine by day table

---

docs/source/index.rst
docs/source/timestamp-algorithm.rst

https://phabricator.endlessm.com/T31728

Add timestamp algorithm into documentation

---

azafea/event_processors/endless/activation/tests/test_activation_parsing.py
azafea/event_processors/endless/activation/v1/handler.py
azafea/event_processors/endless/activation/v1/migrations/3ce72dccdef8_remove_serial_mac_hash.py

- Remove serial and mac_hash from Activation model
- generate a new migration
https://phabricator.endlessm.com/T31744

Remove serial and mac_hash

---

azafea/event_processors/endless/activation/tests/test_activation_validation.py
azafea/event_processors/endless/activation/v1/handler.py
azafea/event_processors/endless/activation/v1/migrations/81cf792f49b2_remove_region_city.py

- Remove region and city from Activation model
- Generate migrations and add SQL to update existings rows and add
constraints on latitude and longitude
- add validation on latitude and longitude on Activation model
- Add tests
https://phabricator.endlessm.com/T31730

Reduce accuracy GeoIP

---

azafea/event_processors/endless/metrics/tests_v3/integration/test_metrics_v3.py
azafea/event_processors/endless/metrics/tests_v3/test_request.py
azafea/event_processors/endless/metrics/v2/model/__init__.py
azafea/event_processors/endless/metrics/v3/model/__init__.py
azafea/event_processors/endless/metrics/v3/model/_base.py
docs/source/events.rst
docs/source/protocol.rst
setup.cfg

https://phabricator.endlessm.com/T31728

Add documentation for new wire format

---

azafea/event_processors/endless/metrics/tests_v2/test_events.py
azafea/event_processors/endless/metrics/v2/model/__init__.py

https://phabricator.endlessm.com/T32200

Handle malformed payload for LinuxPackageOpened

---

azafea/event_processors/endless/image.py
azafea/event_processors/endless/metrics/tests_v3/integration/test_metrics_cli.py
azafea/event_processors/endless/metrics/tests_v3/integration/test_metrics_v3.py
azafea/event_processors/endless/metrics/v3/cli.py
azafea/event_processors/endless/metrics/v3/migrations/05e5217f019f_channel_add_site_and_image_columns_with_index.py
azafea/event_processors/endless/metrics/v3/model/_base.py

https://phabricator.endlessm.com/T32317

Create columns for site and image_id with index on table channel_v3

---

docs/source/protocol.rst

This documents the changes implemented in
567f1336152ef5a6a9d0cba87a0041766c46b1af and
cb969ecf9c47ddd2639d56c0ed22a7a052dda5b9.
https://phabricator.endlessm.com/T32670

Update protocol docs for monthly aggregate event changes

---

azafea/event_processors/endless/metrics/v3/migrations/63f2d8b9636e_add_split_flatpak_repo_stats_event.py

https://phabricator.endlessm.com/T32790

metrics: Add migration for SplitFlatpakRepoStats event table

---

azafea/event_processors/endless/metrics/tests_v3/test_events.py
azafea/event_processors/endless/metrics/v3/migrations/9d6a1a667f01_add_checkpointblocked_tables.py
azafea/event_processors/endless/metrics/v3/model/__init__.py

I chose not to add a _v3 suffix to the table names because:
a. It is incredibly ugly
b. I hope that in time we can retire the old tables
https://phabricator.endlessm.com/T35250

Add CheckpointBlocked{Daily,Monthly} events

---

azafea/event_processors/endless/metrics/tests_v2/integration/test_metrics_v2.py
azafea/event_processors/endless/metrics/tests_v2/test_events.py
azafea/event_processors/endless/metrics/v2/migrations/efbe5d59afbd_remove_monitorconnected_and_.py
azafea/event_processors/endless/metrics/v2/model/__init__.py
azafea/event_processors/endless/metrics/v2/model/_base.py

We do not have a use for this data.
https://phabricator.endlessm.com/T33684

Discard MonitorConnected and MonitorDisconnected
