endlessm/azafea

azafea/event_processors/activation/v1.py, azafea/event_processors/ping/v1.py, azafea/tests/integration/activation/test_activation_v1.py, azafea/tests/integration/ping/test_ping_v1.py
While making some of the requested queries to the DB, I found some interesting indexes to have, which are added here.
The `updated_at` columns was deemed unnecessary and is now removed.
Finally, this makes ping inserts faster by removing one query entirely.
=> Some model changes to the activation/ping processors

azafea/model.py
With sequence events, we are going to have some nullable relationships.
In addition, we're seeing errors in production where some ping events
don't have a ping configuration, and the printing error is masking the
underlying one.
As a result, the method calculating the string representation needs to
take that into account.
=> model: Improve the string representation

azafea/event_processors/ping/v1.py, azafea/tests/integration/ping/test_ping_v1.py
Older images had a bug where they wouldn't send a count when it was 0:
https://github.com/endlessm/eos-phone-home/commit/7145393a1038e9dccfa990836b53dbd11e48835a
We continue receiving pings from such old images, and as such we need to
be able to handle them gracefully.
cc @ramcq
=> ping: Handle missing counts

azafea/event_processors/activation/v1.py
We did it for pings, but somehow forgot about it for activations.
=> activation: Normalize vendors on incoming requests

azafea/model.py, azafea/tests/integration/nullableboolean/test_nullableboolean.py
The NullableBoolean type allows inserting records with a column which
can be either True, False or None, while properly handling unicity
constraints.
To do that is uses a string enum with three states ('true', 'false' and
'unknown') to the Python values (True, False and None).
However, when trying to filter queries on such a column being None in
Python, SQLAlchemy would generate an SQL with "column IS NULL", instead
or the expected "column = 'unknown'.
This commit fixes that.
Fortunately, we had never done such queries in Python yet, so this bug
didn't actually cause any trouble.
=> model: Fix queries on nulleable booleans

azafea/event_processors/metrics/events/__init__.py, azafea/event_processors/metrics/tests/integration/test_metrics_v2.py
Turns out those are always a code made of 3 upper-case letters, rather
than the full name of the vendor.
https://en.wikipedia.org/wiki/Extended_Display_Identification_Data#Structure,_version_1.4
If we really want to normalize these, it will have to be with its own
mapping.
Fortunately this hasn't been deployed yet.
=> metrics: Do not normalize the display vendors

azafea/event_processors/metrics/request.py, azafea/event_processors/metrics/tests/integration/test_metrics_v2_import.py, azafea/event_processors/metrics/v2.py, azafea/event_processors/metrics/v2_import.py
We are going to import the historical data from Cassandra dumps. The
import process will be just like new incoming data: historical records
are inserted into Redis by the import script and Azafea pulls them from
there.
However, with this change, the import script will be able to put them in their own dedicated queue.
This serves 2 purposes:
1.  since Azafea pulls events from multiple queues, in the order they
were configured, we can configure the import queue after the other
ones so that incoming events are treated with priority;
2.  we can import the data slightly differently, without storing the
serialized forms of the requests, to save disk space; this is ok because we already
have the serialized data in the Cassandra dumps, and we will eventually remove this column anyway once we're …
=> Some change for the metrics import

azafea/event_processors/metrics/tests/test_events.py, azafea/event_processors/metrics/tests/test_utils.py, azafea/event_processors/metrics/utils.py
In #37 @danigm added new event models for the Hack Clubhouse application.
I didn't ask for tests to be added because the events looked simple enough, and didn't expect any surprise.
That was a failure on my part, because they couldn't actually work: the `HackClubhouseProgress` event uses `azafea.event_processors.metrics.utils.get_asv_dict()` to parse their payload, and one of the dict values is an `as` variant, which `get_asv_dict()` didn't know how to handle.
As a result, trying to push new `HackClubhouseProgress` events through Azafea would only lead to `NotImplementedError`s. :slightly_frowning_face: 
This merge requests fixes that by adding the missing implementation, and adds unit tests for the Hack Clubhouse events.
In fact, this adds unit tests for all the currently known events. …
=> Fix the Hack Clubhouse events

azafea/event_processors/metrics/events/__init__.py, azafea/event_processors/metrics/tests/test_events.py
This patch adds a new metric emitted in the Hack clubhouse to track user
activation or deactivation of the Hack mode in EOS.
=> metrics: Add hack mode metric

azafea/event_processors/metrics/events/__init__.py, azafea/event_processors/metrics/tests/test_events.py, azafea/event_processors/metrics/utils.py
The pathways attribute as sent by clients is an array of string
variants, not an array of strings.
I was also a bit unhappy with using the generic `get_asv_dict` function to parse this event when we know exactly what the payload is supposed to contain, so in this change I'm also making the code validate the payload.
=> metrics: Fix hack clubhouse events

azafea/event_processors/metrics/events/_base.py, azafea/event_processors/metrics/tests/integration/test_metrics_v2.py
A bug on client machines causes them to send those events for system
users in some cases, but with an empty payload.
There isn't much we can do about those, so let's discard them instead of
piling them up in the invalid table.
=> metrics: Ignore "user logged in" events with empty payloads

Dockerfile, Pipfile, Pipfile.lock, azafea/logging.py, setup.cfg
This updates the dependencies to their latest versions. Nothing important, but nothing with the potential for breakage either.
However, the last pydantic comes with a new mypy plugin, which is enabled in this merge request, to better catch typing issues.
This merge request also removes some build dependencies once they are not needed any more when building the Docker image, making the image a bit smaller.
Finally, this enables Python warnings when running with increased verbosity, which can help finding and fixing issues during development.
=> Dependencies, warnings and linting

azafea/config/__init__.py, azafea/tests/test_cli.py, azafea/tests/test_config.py
This validates the configuration file all at once, so that all errors are reported together, instead of only reporting the first one.
This also changes the validation code so that Azafea only warns about default password when the configuration file is valid.
=> Some configuration validation improvements

azafea/cli/__init__.py, azafea/cli/commands.py, azafea/config/__init__.py, azafea/processor.py, azafea/tests/integration/__init__.py, azafea/tests/test_cli.py, azafea/tests/test_config.py, azafea/tests/test_processor.py, azafea/tests/test_utils.py, azafea/utils.py, docs/source/configuration.rst, docs/source/design.rst, docs/source/index.rst, docs/source/queue-plugins.rst
This first does some refactoring then adds the capability for queue plugins to provide their own CLI subcommands to the main `azafea` command.
No such command is provided, they will come in future pull requests.
=> Support per-queue commands 

Pipfile.lock, azafea/event_processors/metrics/events/_base.py, azafea/event_processors/metrics/tests/test_events.py, azafea/event_processors/metrics/v2/handler.py
After this commit, all aggregate events will always be treated as
unknown.
I've had enough of this unused, untested code. We can bring it back when
we actually have some aggregate events.
=> metrics: Remove most of the code for aggregate events

azafea/event_processors/activation/v1/cli.py, azafea/event_processors/activation/v1/handler.py, azafea/event_processors/metrics/events/_base.py, azafea/event_processors/metrics/v2/cli.py, azafea/event_processors/metrics/v2/handler.py, azafea/event_processors/ping/v1/cli.py, azafea/event_processors/ping/v1/handler.py, azafea/model.py, azafea/tests/conftest.py, azafea/tests/integration/managedb/handler_module.py, azafea/tests/integration/nullableboolean/handler_module.py, azafea/tests/integration/queries/handler_module.py, azafea/tests/integration/queries/test_queries.py, docs/source/queue-plugins.rst
Most management commands operate on data sets too large to be fetched all at once and then iterated on without being OOM-killed.
Until this change we wrote custom query chunking for each such command.
We're going to add more, and copy-pasting this code gets old real quick.
This change brings a new `dbsession.chunked_query(…)` method, and moves the existing management commands to use it.
=> Implement chunked queries

Pipfile, Pipfile.lock, azafea/config/__init__.py, azafea/event_processors/activation/v1/__init__.py, azafea/event_processors/metrics/v2/__init__.py, azafea/event_processors/ping/v1/__init__.py, azafea/model.py, azafea/processor.py, azafea/tests/integration/__init__.py
This updates the dependencies, taking care to avoid the latest Mypy as [Pydantic is currently incompatible with it](https://github.com/samuelcolvin/pydantic/issues/1057).
This also moves the attempt at connectiong to PG somewhere where it makes more sense, and where it will be useful for the DB migrations.
Finally, this changes the setup/teardown fixture of the integration tests, also to make things simpler down the road.
I'm pushing this as its own pull request to make the next one smaller.
=> Misc changes

azafea/event_processors/activation/v1/cli.py, azafea/event_processors/metrics/v2/cli.py, azafea/event_processors/ping/v1/cli.py, azafea/model.py
This fixes the definition of the `ChunkedQuery`, removing the unnecessary inheritance.
This also fixes the help output of the per-queue subcommands so they show the default values for options.
=> Misc fixups

azafea/event_processors/metrics/tests/integration/test_metrics_cli.py
I forgot this when I implemented replaying unknown aggregate events.
=> tests: Add a missing check

azafea/event_processors/metrics/events/__init__.py, azafea/event_processors/metrics/events/_base.py, azafea/event_processors/metrics/tests/integration/test_metrics_cli.py, azafea/event_processors/metrics/v2/cli.py, azafea/model.py, azafea/tests/integration/queries/test_queries.py
This brings 2 improvements so that the commands aren't so long:
1. there is no point going over all the unknown events we already know will still be unknown after the replay, so those "unknown unknowns" are entirely skipped, resulting in a huge speed bump in some cases;
2. the admin running the command can now specify a `--no-more-than` option, so that in the event that there are still too many "known unknowns" to go through, they can do it piecemeal, instead of staring at the progress bar for hours.
=> metrics: Make it faster to replay unknown events

azafea/event_processors/metrics/events/__init__.py, azafea/event_processors/metrics/machine.py, azafea/event_processors/metrics/tests/integration/test_metrics_db_functions.py, azafea/event_processors/metrics/tests/integration/test_metrics_v2.py, azafea/event_processors/metrics/v2/migrations/33c19f68197d_add_the_machine_mapping_table.py, azafea/event_processors/metrics/v2/migrations/7f4c0154d6cd_add_image_functions.py
Most queries we want to run on the database are based on the image "product" and "personality".
At the moment that implies joining the metrics_request_v2 and image_version tables, filtering by the result of a function you must write in the query, then joining that with the tables you want to actually query.
This branch makes it significantly easier by adding a machine/image mapping, and a couple of functions to get the image product and personality for a given request.
This will also be the base of the row-level security for the Endless deployment: a given user will only have access to the requests corresponding to machines running a given product/personality. (#46)
=> metrics: Make queries simpler

.travis.yml
Now that we can have Docker images for development, this also moves the CI to use it instead of whatever Travis does to their poor old Ubuntu 16.04.
Controlling our test environment with containers frees us from the underlying host, so we can use a more minimal Travis host image and upgrade to a newer Ubuntu for the host.
Finally, this fixes a minor problem with our CI where some parts of an undesired PostgreSQL version would remain installed. While that never caused any problem, removing it avoids all potential for any such problems in the future.
=> Embrace containers for the CI

.travis.yml
Try to improve the time it takes for a ci run by:
- Caching Docker images.
- Doing less for the lint job.
Don't merge this yet, the PR is for running the CI.
=> ci: Use containerized services in Travis

azafea/cli/commands.py, azafea/config/__init__.py, azafea/event_processors/activation/v1/cli.py, azafea/event_processors/metrics/v2/cli.py, azafea/event_processors/ping/v1/cli.py, azafea/model.py, azafea/processor.py, azafea/tests/integration/__init__.py, azafea/tests/test_cli.py, azafea/tests/test_config.py, azafea/tests/test_model.py, docs/source/configuration.rst
PostgreSQL's libpq supports many connection arguments:
https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS
SQLAlchemy makes it easy to pass them down to PsycoPG2 and libpq:
https://docs.sqlalchemy.org/en/13/core/engines.html#custom-dbapi-args
This commit introduces a new "connect_args" configuration table, nested
under the "postgresql" one.
It can be passed arbitrary key/values, like "sslmode" or
"connect_timeout" for example.
Fixes #74
=> config: Allow passing PostgreSQL connection arguments

Dockerfile
Pip and pipenv store a lot of stuff in ~/.cache, dropping it shaves about 13% from the final image size.
=> docker: Remove the user cache

azafea/utils.py
This should avoid getting all the progress output at the end in the
CloudWatch logs.
=> utils: Always flush the progress bar

azafea/tests/test_utils.py, azafea/utils.py
Simply flushing each progress output wasn't enough to get them to appear
instantly in the CloudWatch logs, which still seems to buffer them.
This should hopefully solve the problem, and is nicer anyway when
redirecting the command output.
=> utils: Add a newline to the progress bar when not in a TTY

azafea/event_processors/metrics/v2/migrations/f7b3720152d2_explicitly_specify_the_public_.py
The PostgreSQL autovacuum workers keep failing their ANALYZE step in
production:
```
2020-01-21 11:56:53 UTC::@:[22993]:ERROR:  relation "metrics_machine" does not exist at character 102
2020-01-21 11:56:53 UTC::@:[22993]:QUERY:  SELECT (
SELECT reverse(split_part(reverse(image_id), '.', 1)) AS personality
FROM metrics_machine
WHERE metrics_machine.machine_id = _machine_id
)
2020-01-21 11:56:53 UTC::@:[22993]:CONTEXT:  PL/pgSQL function public.get_image_personality(text) line 3 at RETURN
automatic analyze of table "azafea.public.metrics_request_v2"
```
This is because they operate in a different context where they
apparently don't assume the "public" tablespace to be the default.
This migration recreates the functions (recreating the corresponding
indexes) to fix that, by explicitly …
=> metrics: Fix the image product/personality functions

azafea/event_processors/metrics/events/__init__.py, azafea/event_processors/metrics/tests/test_events.py, azafea/event_processors/metrics/v2/migrations/d0d01392a0ee_add_hack_news_quest_link_event.py
This patch adds a new metric emitted in the Hack clubhouse to track user
engagement with the release notes inside the app. This will track the
quests launched from the hack news page links.
https://phabricator.endlessm.com/T29192
=> metrics: Add hack news quest link event

Dockerfile
Building the Docker image requires installing Pipenv, then using it to install the Azafea dependencies in a virtualenv.
The Azafea dependencies are pinned to specific versions, so every time we build the Docker image we get the exact same virtualenv, until we bump those dependencies.
However, Pipenv itself doesn't pin its dependencies, so we get the latest of each one of them.
This has no impact on what ends up in the virtualenv, which is correctly reproducible.
It does have an impact on installing Pipenv though, and this just happened and broke the build of our Docker image.
The latest Pipenv release (which we have been using for a while and hasn't changed) has the following requirements:
* certifi
* pip>=9.0.1
* setuptools>=36.2.1
* virtualenv
* virtualenv-clone>=0.2.5
A recent …
=> docker: Preinstall setuptools and wheel

Pipfile, Pipfile.lock, azafea/event_processors/endless/activation/tests/integration/test_activation_cli.py, azafea/event_processors/endless/activation/tests/integration/test_activation_v1.py, azafea/event_processors/endless/activation/tests/test_activation_parsing.py, azafea/event_processors/endless/activation/v1/handler.py, azafea/event_processors/endless/activation/v1/migrations/3bf359e3c86c_store_the_parsed_image_components.py, azafea/event_processors/endless/image.py, azafea/event_processors/endless/metrics/machine.py, azafea/event_processors/endless/metrics/tests/integration/test_metrics_cli.py, azafea/event_processors/endless/metrics/tests/integration/test_metrics_db_functions.py, azafea/event_processors/endless/metrics/tests/integration/test_metrics_v2.py, azafea/event_processors/endless/metrics/v2/migrations/3dc06459fc41_store_the_parsed_image_components_as_.py, azafea/event_processors/endless/ping/tests/integration/test_ping_cli.py, azafea/event_processors/endless/ping/tests/integration/test_ping_v1.py, azafea/event_processors/endless/ping/v1/handler.py, azafea/event_processors/endless/ping/v1/migrations/439e90a6874a_store_the_parsed_image_components.py, azafea/event_processors/endless/tests/test_image.py
The OS image id we receive in multiple events has a very specific format, with a few components, all of which are interesting to run queries on.
All the current Endless event processors are changed to do that, sotring the individual components of the image id in the appropriate table.
A specificity of the metrics events is that invalid image ids are never sent by the clients, whereas ping and activations are sent with the special `unknown` image id which need to be treated as valid records.
This also needs to account for an old, long fixed bug, which still generates ping and metrics records unfortunately.
=> Parse the Endless image ids

azafea/event_processors/endless/activation/tests/integration/test_activation_cli.py, azafea/event_processors/endless/activation/v1/cli.py, azafea/event_processors/endless/metrics/tests/integration/test_metrics_v2.py, azafea/event_processors/endless/metrics/v2/cli.py, azafea/event_processors/endless/ping/tests/integration/test_ping_cli.py, azafea/event_processors/endless/ping/v1/cli.py
In #89 we added new columns to the activation, metrics and ping models so that they store the individual components of the image ids, after parsing it.
This merge request introduces new management command to go over the old records, parse the image ids and store the results in the new columns.
---
@adarnimrod: we will need to run those commands after deploying the new Azafea. They can be run in parallel with Azafea running and receiving new events.
They might take a bit of time though, so we will finally be able to test my changes to make the progress output appear during the process in CloudWatch rather than all at the end. :slightly_smiling_face:
=> Parse old Endless images ids

azafea/event_processors/endless/metrics/events/__init__.py, azafea/event_processors/endless/metrics/tests/integration/test_metrics_cli.py, azafea/event_processors/endless/metrics/tests/integration/test_metrics_v2.py
The code was written to keep a single image version event for each database transaction… even if they came from different metrics requests.
This is wrong, and this commit fixes it so that we only keep a single image version event per request.
The risk is theoretical at the moment because Azafea processes one request at a time, so the metrics request and the db session effectively have the same life cycle.
However, this has the potential to blow and cause data loss due to changes in the future if we changed that, so let's fix it now before it causes trouble.
=> metrics: Improve the image version deduplication

azafea/event_processors/endless/metrics/tests/integration/test_metrics_cli.py, azafea/event_processors/endless/metrics/v2/cli.py
This is necessary to populate the machine mapping table without waiting for a new image version event from each deployed machine, some of which connect to the Internet very infrequently.
=> metrics: Add a command to replay past image version events

azafea/event_processors/endless/metrics/v2/cli.py
Too bad I caught the problem when running the command in production. /o\
=> metrics: Fix progress reporting for a command

azafea/event_processors/endless/metrics/events/__init__.py, azafea/event_processors/endless/metrics/tests/integration/test_metrics_cli.py, azafea/event_processors/endless/metrics/tests/integration/test_metrics_v2.py, azafea/event_processors/endless/metrics/v2/cli.py
Much like the image version events, those are only interesting to get once.
Deduplicating them entirely might be a bit hard, coordinating between multiple processes, but we can easily deduplicate them per request.
This does that for incoming events, and adds a command to go over the old events and deduplicate them after the fact.
=> Deduplicate dualboot and live USB events

azafea/event_processors/endless/metrics/events/__init__.py, azafea/event_processors/endless/metrics/machine.py, azafea/event_processors/endless/metrics/tests/integration/test_metrics_cli.py, azafea/event_processors/endless/metrics/tests/integration/test_metrics_v2.py, azafea/event_processors/endless/metrics/tests/test_events.py, azafea/event_processors/endless/metrics/v2/cli.py, azafea/event_processors/endless/metrics/v2/migrations/a6e10c2e3f79_add_a_demo_property_to_the_machine.py, azafea/event_processors/endless/metrics/v2/migrations/b3ad0a81aa3c_add_the_demo_mode_event.py, azafea/event_processors/endless/metrics/v2/migrations/b4cf8c78ca97_make_the_machine_s_image_id_optional.py, azafea/event_processors/endless/metrics/v2/migrations/cced14e41a46_add_a_dualboot_property_to_the_machine.py, azafea/event_processors/endless/metrics/v2/migrations/d99f33473540_add_a_live_property_to_the_machine.py
That's really what they are, since they can't be changed, and they probably could have been sent by clients as request attributes rather than events.
But things are what they are, and we get them as events.
However we can still do better on the server side, by storing them as columns in the machine table, making queries much easier.
This change adds the columns, and populates them for incoming records. Commands to replay old events are also included.
=> metrics: Add live, demo and dualboot as property of the machines

.travis.yml, Dockerfile, config.toml.j2, entrypoint
In production in Endless, we use a different Dockerfile with a slightly
different setup. The main points are using the Alpine variant of the
Python base image and rendering a `config.toml` file from a template and
environment variable. This commit uses (almost) exactly the same
Dockerfile that we use in production since Azafea was deployed and it
can be argued that it's the most tested one. We don't have a dev/ prod
image so that build argument is dropped.
=> Use the same Dockerfile as we use in production.

.gitignore, CONTRIBUTING.md, azafea/event_processors/endless/metrics/new-event.rst, azafea/event_processors/endless/metrics/v2/migrations/9bd33e9778fa_add_parental_controls_events.py, docs/source/install.rst
This adds the missing database migration script for the new parental controls events, which I neglected to add in the initial commit.
I haven’t tested this, since setting up postgresql and redis containers in order to do so is a fairly involved effort. We’ll see if it works when doing the test database migrationm
https://phabricator.endlessm.com/T28742
=> T28742 Parental controls migration

docs/source/install.rst
- Use a volume instead of a directory (it's not likely that we're going
to inspect the files there and we can still re-use it).
- Specify the username and database to create (the user will own that
database). Instead of going through `psql` and doing that by hand.
=> Docs: Fix and simplify the Posgres installation.

setup.cfg
Configuring flake8 in its own section gives the opportunity to third-party tools to use this configuration too. It can, for example, be useful for text editors with embedded linters.
Of course, it works with pytest too.
=> Configure flake8 outside of pytest configuration

azafea/event_processors/endless/metrics/events/__init__.py, azafea/event_processors/endless/metrics/tests/integration/test_metrics_cli.py, azafea/event_processors/endless/metrics/v2/cli.py, azafea/event_processors/endless/metrics/v2/migrations/4a49897b47ea_open_app_id_started_at_index.py, azafea/event_processors/endless/metrics/v2/migrations/d4809698244a_add_duration.py
This PR brings two improvements:
- Add an index to improve speed when we want to retrieve data involving start
time and group it by app ID (7086bbf).
- Add a `duration` column allowing Metabase users to query duration with no SQL (0c2f39c).
`duration` is a float representing difference between `stopped_at` and `started_at` in seconds. It’s implemented as a SQLAlchemy default value, as the lines are not supposed to be changed.
https://phabricator.endlessm.com/T29220
=> Improve shell_app_is_open to allow easier and faster reports

azafea/event_processors/endless/metrics/events/__init__.py, azafea/event_processors/endless/metrics/tests/integration/test_metrics_cli.py, azafea/event_processors/endless/metrics/tests/test_events.py, azafea/event_processors/endless/metrics/v2/cli.py
OS information fields get useless extra quotes and field in the payload.
This pull request:
- ~~drops the useless `name` column,~~
- strips the useless quotes around `version` (and `name`) before inserting new rows,
- adds a command removing useless quotes from `version` (and `name`) in database.
~~This is a draft because:~~
- ~~it needs endlessm/eos-metrics-instrumentation#88 (draft too),~~
- ~~it includes an Alembic migration and thus has to be adjusted when #109 is merged.~~
https://phabricator.endlessm.com/T29322
=> Strip useless quotes and field from OS information

azafea/event_processors/endless/metrics/events/__init__.py, azafea/event_processors/endless/metrics/events/_base.py, azafea/event_processors/endless/metrics/tests/test_events.py
Empty values are sent by old versions of eos-metrics-instrumentation because gnome-initial-setup stores them in the configuration file by mistake. These empty strings are useless, we do not want to keep them in the database.
https://phabricator.endlessm.com/T29561
=> Do not store empty values of location label information

azafea/event_processors/endless/metrics/events/__init__.py, azafea/event_processors/endless/metrics/tests/integration/test_metrics_cli.py, azafea/event_processors/endless/metrics/tests/integration/test_metrics_v2.py, azafea/event_processors/endless/metrics/tests/test_events.py, azafea/event_processors/endless/metrics/v2/cli.py, azafea/event_processors/endless/metrics/v2/migrations/9184d25ca795_drop_os_name_column.py
This PR removes the `name` column from the `os_version` table. This value is ulesess as it always is "Endless".
This is a draft because:
- ~it includes (and should be merged after) #111~ (merged),
- ~it includes an Alembic migration and thus has to be adjusted when #109 is merged~ (changed).
https://phabricator.endlessm.com/T29322
=> Drop the OS name column

azafea/event_processors/endless/metrics/events/__init__.py, azafea/event_processors/endless/metrics/v2/migrations/2b8c64885884_invert_shell_app_is_open_index.py
Inverting the columns order gives faster requests for many use cases.
https://phabricator.endlessm.com/T29220#anchor-836405
=> Invert order of columns for the ShellAppIsOpen index

azafea/event_processors/endless/activation/tests/integration/test_activation_cli.py, azafea/event_processors/endless/activation/tests/integration/test_activation_v1.py, azafea/event_processors/endless/activation/tests/test_activation_validation.py, azafea/event_processors/endless/activation/v1/cli.py, azafea/event_processors/endless/activation/v1/handler.py, azafea/event_processors/endless/activation/v1/migrations/a9e5d0f9b1cf_alpha_2_3_activation.py, azafea/event_processors/endless/country.py, azafea/event_processors/endless/ping/tests/integration/test_ping_cli.py, azafea/event_processors/endless/ping/tests/test_ping_validation.py, azafea/event_processors/endless/ping/v1/cli.py, azafea/event_processors/endless/ping/v1/handler.py, azafea/event_processors/endless/ping/v1/migrations/f2d6141dbece_alpha_2_3_ping.py
This PR includes these changes:
- DB migration allowing both alpha2 and alpha3 codes in PostgreSQL,
- SQLAlchemy changes allowing ~~only alpha2~~ alpha2 and alpha3 codes when inserting new records,
- CLI commands added for country code migration in `ping_v1` and `activation_v1`.
https://phabricator.endlessm.com/T29210
=> Store 2-letter country codes in database

azafea/event_processors/endless/metrics/events/__init__.py, azafea/event_processors/endless/metrics/tests/integration/test_metrics_v2.py, azafea/event_processors/endless/metrics/tests/test_events.py, azafea/event_processors/endless/metrics/v2/migrations/961fbbaf2cf7_add_the_underscan_enabled_event.py
This commit is "inspired" by the following one:
metrics: Process the "demo mode entered" events
https://phabricator.endlessm.com/T30766
=> metrics: Process "underscan enabled" events

azafea/event_processors/endless/metrics/events/_base.py, azafea/event_processors/endless/metrics/request.py, azafea/event_processors/endless/metrics/v2/migrations/29c26262aa70_add_day_index_on_machine_by_day_table.py, azafea/event_processors/endless/metrics/v2/migrations/53fffde5ad55_merge_migrations.py, azafea/event_processors/endless/metrics/v2/migrations/98078d059259_add_index_on_started_at_and_occured_at.py, docs/source/queue-plugins.rst
The alembic tree had 3 heads: e7c7d5f2e4df, 7e12d8f42f28, eba4a3cf4aae. As 3 branches have already been deployed on production, we can’t rebase. We have to merge these heads into one.
=> Merge alembic migrations

Pipfile, azafea/event_processors/endless/metrics/events/__init__.py, docs/source/conf.py, docs/source/metabase.py
See https://phabricator.endlessm.com/T30895.
**This PR has to be merged after #127.**
The documentation for known tables and their fields can be uploaded using:
~`sphinx-build docs/source/ docs/build/html/ -b metabase -D metabase_session=<key> -D metabase_url=<url> -E`~
`sphinx-build docs/source/ docs/build/html/ -b metabase -D metabase_username=<username> -D metabase_password=<password> -D metabase_url=<url> -E`
Environment variables (uppercase) can also be used instead of Sphinx properties.
This code uses Sphinx to gather docstrings from the documentation, translate them from ReST to plain text, and upload them on Metabase. It suffers from many problems that can be solved in other pull requests later if needed.
- Transforming ReST to plain text is painful. Docutils doesn’t include a …
=> Add a sphinx module to upload documentation on metabase

azafea/event_processors/endless/metrics/events/__init__.py, azafea/event_processors/endless/metrics/machine.py, azafea/event_processors/endless/metrics/tests/integration/test_metrics_cli.py, azafea/event_processors/endless/metrics/tests/integration/test_metrics_v2.py, azafea/event_processors/endless/metrics/v2/migrations/991574509c57_add_machine_location_columns.py
Instead of storing machine location in events, we can store it in the metrics_machine table and upsert when new events happen.
The deployment creates the new columns and sets the values according to the events already stored in the database.
The event table is not removed yet. This way, we can check that everything is OK for a while, and keep events if anything goes wrong.
This is the first step of https://phabricator.endlessm.com/T30471.
=> Store machine location into metrics_machine table

azafea/event_processors/endless/metrics/request.py, azafea/event_processors/endless/metrics/tests/integration/test_metrics_cli.py, azafea/event_processors/endless/metrics/tests/integration/test_metrics_db_functions.py, azafea/event_processors/endless/metrics/tests/integration/test_metrics_v2.py, azafea/event_processors/endless/metrics/v2/migrations/8eb67a73775b_remove_the_serialized_request_column.py
I had decided to keep that originally so that in case of a dramatic
failure we would be able to reparse everything from the raw bytes to fix
whatever issue had come up.
It seems like things are working just fine though, so the time has come
to remove it and reclaim some disk space.
https://phabricator.endlessm.com/T31411
=> metrics: Drop the serialized request column

.github/workflows/docker-hub.yml
GitHub Actions workflow to publish the Docker image to Docker Hub. Use
the image built during the tests workflow. Only run on changes to the
master branch and only after the test workflow has finished
successfully.
https://phabricator.endlessm.com/T31467
=> Publish the Docker image to Docker Hub.

.dockerignore, .github/workflows/tests.yml, docs/source/queue-plugins.rst
Sphinx is pretty tolerant while building the documentation, and we already missed silent errors and warnings for documentation on production.
The problem appeared again during the metrics v2/v3 reorganization, with no obvious warning sign being raised. Testing documentation builds in CI should avoid problems in the future.
Note that this commit includes docs in the Docker image.
=> Test documentation builds in CI

docs/source/metabase.py
See https://phabricator.endlessm.com/T32311.
=> Don’t crash when no table needs a Metabase documentation update

azafea/event_processors/endless/metrics/tests_v3/test_request.py, azafea/event_processors/endless/metrics/v3/model/_base.py, azafea/event_processors/endless/metrics/v3/utils.py
This is the last part of the timestamp algorithm:
https://azafea.readthedocs.io/en/latest/timestamp-algorithm.html#server-side
"When the server receives a network request, it will first examine the network request absolute time to see if it varies significantly from its own (trusted) clock. If it does, some special action will be taken with that request, such as putting it in its own special table or attempting to correct the timestamp in some fashion."
Our "attempt to correct the timestamp" happens when:
- the request is received before it has been sent (1 second tolerance),
- the request is received a long time after it has been sent (10 minutes tolerance).
In these two cases, we prefer to use the server’s clock, because the client’s clock is obviously wrong. …
=> Use the server’s clock when it’s obviously better than the client’s

readthedocs.yml
Install system packages required for python packages and specify the python version to Read the Docs. This should hopefully get things moving again and make the environment more consistent.
https://phabricator.endlessm.com/T32700
=> Read the Docs environment

azafea/event_processors/endless/metrics/tests_v2/test_utils.py, azafea/event_processors/endless/metrics/tests_v3/integration/test_metrics_v3.py, azafea/event_processors/endless/metrics/tests_v3/test_events.py, azafea/event_processors/endless/metrics/tests_v3/test_utils.py, azafea/event_processors/endless/metrics/v2/utils.py, azafea/event_processors/endless/metrics/v3/model/__init__.py, azafea/event_processors/endless/metrics/v3/utils.py
This metric is sent by the `eos-split-flatpak-repo` script to record
statistics about splitting the system Flatpak repo from the system
OSTree repo.
The corresponding client side is in endlessm/eos-boot-helper#361.
https://phabricator.endlessm.com/T32790
=> metrics: Add SplitFlatpakRepoStats event

azafea/event_processors/endless/metrics/v3/model/_base.py, docs/source/events.rst
As described in the main commit, we have learned what we wanted to learn by collecting this event. We can now remove the data from the database and stop storing new submissions.
https://phabricator.endlessm.com/T35061
=> Drop tour response event

azafea/event_processors/endless/activation/tests/integration/test_activation_cli.py, azafea/event_processors/endless/activation/tests/integration/test_activation_v1.py, azafea/event_processors/endless/activation/tests/test_activation_parsing.py, azafea/event_processors/endless/metrics/tests_v2/integration/test_metrics_cli.py, azafea/event_processors/endless/metrics/tests_v2/integration/test_metrics_db_functions.py, azafea/event_processors/endless/metrics/tests_v2/integration/test_metrics_v2.py, azafea/event_processors/endless/metrics/tests_v3/integration/test_metrics_cli.py, azafea/event_processors/endless/ping/tests/integration/test_ping_cli.py, azafea/event_processors/endless/ping/tests/integration/test_ping_v1.py, azafea/event_processors/endless/ping/tests/test_ping_parsing.py
https://blog.ganssle.io/articles/2019/11/utcnow.html lays out why this function is bad. In fact I believe the usage in the tests is safe. However Python 3.12 will formally deprecate this function: https://discuss.python.org/t/deprecating-utcnow-and-utcfromtimestamp/26221
Replace it with the recommended (and shorter!) alternative.
=> tests: Stop using future-deprecated datetime.utcnow()

requirements.readthedocs.txt, update-rtd-requirements
Since pipenv 2022.8.13, `pipenv lock --requirements` has been removed in favor of the `pipenv requirements` command[1]. Adjust the RTD requirements script accordingly and regenerate the requirements file with the minor sorting change from current pipenv.
1. https://github.com/pypa/pipenv/blob/main/CHANGELOG.md#2022813-2022-08-13
=> Adjust RTD requirements scripts for pipenv >= 2022.8.13

azafea/event_processors/endless/metrics/tests_v3/integration/test_metrics_v3.py, azafea/event_processors/endless/metrics/v3/handler.py, azafea/event_processors/endless/metrics/v3/model/__init__.py
When processing a submitted request, we ensure that the request channel
has a corresponding Channel record, creating it if needed.
Previously this was done by attempting to insert a new Channel every
time, and, if this fails due to the uniqueness constraint (on the image
ID and site dictionary) being violated, only then trying to fetch an
existing row.
This is correct in the sense that it will always result in the channel
being present in the table. The problem is that attempting to insert a
channel consumes an id from the underlying sequence that channel IDs are
generated from, and rolling back on the constraint violation does not
roll back the sequence. So, each request consumes a channel ID, whether
or not the channel has been seen before.
In October 2022 when I first noticed this …
=> Avoid incrementing channel ID sequence if not needed

azafea/event_processors/endless/metrics/tests_v3/test_events.py, azafea/event_processors/endless/metrics/v3/model/__init__.py, azafea/event_processors/endless/metrics/v3/model/_base.py
We would like to adjust the CPU information sent by eos-metrics-instrumentation to include CPU flags: statistics about how widely-supported certain extensions are will allow the freedesktop-sdk project to quantify the impact of (for example) assuming certain x86-64 extensions are present.
Previously, events with some given UUID are expected to have a payload of one specific GVariant type, and those types are typically not something extensible like `a{sv}`. This is quite annoying when we want to add a new field, particularly in this CPU data which just ends up being stuffed into a JSONB column in the database.
So, allow event models to specify a tuple of accepted GVariant types; then take advantage of this in the ComputerInformation model to understand a new type with an extra string of …
=> Ingest CPU flags from ComputerInformation event

.dockerignore, .gitignore, Dockerfile, config.toml.j2, docs/source/install.rst
The real fix is in [docker: Use config generated by entrypoint](https://github.com/endlessm/azafea/commit/cb8c3f091320d9c99310227ed205ad65b5dba009). This instructs azafea to use the templated configuration file so that the environment variables set for the container actually work. The others are some polish and documentation I came across while looking at this.
Fixes: #188
=> Handle configuration in Docker correctly

.dockerignore, .gitignore, Dockerfile, azafea/cli/commands.py, azafea/config/__init__.py, azafea/processor.py, azafea/tests/integration/__init__.py, azafea/tests/test_cli.py, azafea/tests/test_config.py, azafea/tests/test_processor.py, config.toml.j2, docs/source/configuration.rst, docs/source/install.rst
Currently if you want to connect to an SSL enabled Redis server, you
need to use a TLS proxy. However, redis-py supports TLS connections
natively[1] (even in our old version). Expose that as an `ssl` boolean
in the configuration.
1. https://redis-py.readthedocs.io/en/3.5.3/index.html#redis.Redis
Fixes: #190
This is on top of #189. I'm happy to rebase if that's accepted or rework if it's not.
I tested this with ElasticCache and it seems to work.
=> Support Redis SSL connections

azafea/event_processors/endless/image.py, azafea/event_processors/endless/tests/test_image.py
Endless OS 4.0.x and 5.0.x would submit this string if the image version could not be read as valid UTF-8 from disk. (This string comes from within GLib if you pass a NULL pointer as the argument for a 's' type code in a call to g_variant_new().)
This is fixed in Endless OS 5.1.0 and newer, but we have many requests in the error queue which are failing to be loaded for this reason.
Treat "[Invalid UTF-8]" the same as "unknown".
https://phabricator.endlessm.com/T35279
https://github.com/endlessm/eos-event-recorder-daemon/commit/13d533b5d47cc592545cbcb63cb17c28df860762
=> endless: Handle image ID "[Invalid UTF-8]" like "unknown"

.github/workflows/metabase.yml
An API key is the preferred way to authenticate to the Metabase API. The metabase builder supports API keys using the `METABASE_API_KEY` environment variable since 7337d7a.
https://phabricator.endlessm.com/T32367
This depends on https://github.com/endlessm/eos-administration/pull/1448.
=> github: Use API key instead of username/password

docs/source/metabase.py
Per the documentation[1][2], the parameters in the Table and Field update endpoints are "nullable value must be a non-blank string". Presumably earlier versions of Metabase converted blank strings to null internally. Make sure we use `None` if the stripped string value is empty.
1. https://www.metabase.com/docs/latest/api/table#put-apitableid
2. https://www.metabase.com/docs/latest/api/field#put-apifieldid
https://phabricator.endlessm.com/T32367
=> docs/metabase: Null blank string values
